### ISSUE TITLE
Actuator endpoints are forbidden

### ISSUE THREAD

**Issue by essare** [F43nd1r/Acrarium#227]
First I'd like to thank the developers for this awesome project.

I'm using Acrarium's docker image `f43nd1r/acrarium:latest` in Kubernetes and I passed Actuator's properties as Environment variable to enable it, however when I visit `/actuator/health` I get `HTTP Status 403 – Forbidden`

This is how I passed actuator properties to Acrarium container:

```
containers:
     - name: acrarium-container
       image: f43nd1r/acrarium:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 8080
       env:
         - name: SPRING_APPLICATION_JSON
           value: '{ "management": { "endpoints": { "enabled-by-default": true }, "endpoint": { "health": { "show-details": "always", "probes": { "enabled": true } } }, "health": { "livenessState": { "enabled": true }, "readinessState": { "enabled": true } } } }'

```

please permit actuator endpoints in your security configuration so we can profit from Actuator.
Thanks.

**Comment by essare** [comment]
Thanks! But what if i wanted I to give actuator endpoints to Kubernetes for liveness and readiness probe ?

**Comment by F43nd1r** [comment]
Then you'll need to provide kubernetes with the credentials to a user account. You can create one with just the API permission.

**Comment by essare** [comment]
Can you please provide an example on how to pass these credentials to the acrarium container ?

**Comment by F43nd1r** [comment]
Not sure what you need. This?
```
curl -u username:password https://server:8080/actuator/health
```

**Comment by essare** [comment]
My Acrarium deployment is like this:
```
containers:
        - name: acrarium-container
          image: f43nd1r/acrarium:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: 

             # mysql env properties here...

            - name: SPRING_APPLICATION_JSON
              value: '{ "management": { "endpoints": { "enabled-by-default": true }, "endpoint": { "health": { "show-details": "always", "probes": { "enabled": true } } }, "health": { "livenessState": { "enabled": true }, "readinessState": { "enabled": true } } } }'

      livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3

          readinessProbe:
            httpGet:
               path: /actuator/health/readiness
               port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3

```
I really don't know how to pass the authentication to the container.
