### ISSUE TITLE
Unable to upload large Proguard mapping files  

### ISSUE THREAD

**Issue by AChep** [F43nd1r/Acrarium#464]
The error is 
```
org.springframework.dao.TransientDataAccessResourceException: jOOQ; SQL [insert into `version` (`app_id`, `code`, `flavor`, `name`, `mappings`) values (?, ?, ?, ?, ?) on duplicate key update `version`.`name` = ?, `version`.`mappings` = ?]; Packet for query is too large (175,025,917 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.
```
my mapping.txt file is 90mb large.

**Comment by F43nd1r** [comment]
Currently the default upload limit is set to 100mb. Are you using an old version?

**Comment by AChep** [comment]
@F43nd1r I'm using version `2.0.0-beta06` from f43nd1r/acrarium:next docker image.

**Comment by AChep** [comment]
Here's a docker config I'm using:
```
version: "3.7"

services:
   acrarium_db:
       image: mysql:5.7
       container_name: acrarium-db
       environment:
           MYSQL_ROOT_HOST: '%'
           MYSQL_ROOT_PASSWORD: "***"
           MYSQL_DATABASE: "acrarium"
           MYSQL_USER: "acrarium"
           MYSQL_PASSWORD: "***"
       restart: unless-stopped
       networks:
           - default
       volumes:
           - acrarium_data:/var/lib/mysql
       ulimits:
           nproc: 65535
           nofile:
               soft: 20000
               hard: 40000
       command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   acrarium:
       image: f43nd1r/acrarium:next
       container_name: acrarium
       depends_on:
           - acrarium_db
       restart: unless-stopped
       networks:
           - traefik_default
           - default
       environment:
           SPRING_DATASOURCE_URL: jdbc:mysql://acrarium-db:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
           SPRING_DATASOURCE_USERNAME: "acrarium"
           SPRING_DATASOURCE_PASSWORD: "***"
           SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.MySQL57Dialect
```
