### ISSUE TITLE
Not able to change port : Docker

### ISSUE THREAD

**Issue by adolfdsilva** [F43nd1r/Acrarium#52]
<img width="1051" alt="Screen Shot 2020-04-07 at 2 29 07 PM" src="https://user-images.githubusercontent.com/6647993/78642406-e2b6f200-78dc-11ea-8333-0a6bab42c3fb.png">

Getting error

> Web server failed to start. Port 8080 was already in use.

**Comment by F43nd1r** [comment]
Change only the public port. Port inside the docker container must be 8080

**Comment by adolfdsilva** [comment]
But i don't think it should give error failed to start on 8080 as there is no such port specified.

I'm not a docker expert but, I think the line 

> network_mode:host

 is starting the container in host mode and hence the ports are ignored completely.
I'm trying to create a custom network and put the network_mode as bridge, so I can link the db and front end.


But is there any environment variable for port ?

**Comment by adolfdsilva** [comment]
Ok so if you specify the network_mode as host docker uses the host network. So specifying the ports is useless.

So for now if you use above style of setup the server will run on 8080.

**Comment by F43nd1r** [comment]
All spring boot configurations are available as environment variables.
More specifically, you can set
```
environment:
    SERVER_PORT: 8081
```

**Comment by adolfdsilva** [comment]
Thanks it works.. my final docker compose is 

```
version: "3.7"

services:
    acrarium:
        image: f43nd1r/acrarium:latest
        container_name: acrarium
        network_mode: host
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: acrarium
            SPRING_DATASOURCE_PASSWORD: ****
            SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL57Dialect
            SERVER_PORT: 20101
```
